# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Clone
      run: git clone https://github.com/666hwll/gofluentlycalculator
    - name: CD
      run: cd gofluentlycalculator
    - name: Build
      run: go build -v -x -o calculator64.go gocalc

    - name: Test-1
      run: go run gocalc + 23 34
    - name: Test-2
      run: go run gocalc - 23 34
    - name: Test-3
      run: go run gocalc * 23 34
    - name: Test-4
      run: go run gocalc / 23 0
